# Generated by Django 4.2.2 on 2023-06-09 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="user",
        ),
    ]
